name: blog_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  carousel_slider: ^5.0.0
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
